### ISSUE TITLE
8 segment LED bar

### ISSUE THREAD

**Issue by MykolaKyrylenko** [wokwi/wokwi-elements#104]
We are using the Arduino to teach low level register access (e.g. DDRx, PORTx, PINx) and we need to access all pins on a given port.
For convenience, can an 8 segment LED bar be added.
Similar to this: https://au.rs-online.com/web/p/led-displays/2473056/

Thanks

**Comment by rcwilcox** [comment]
I like this idea.
As a work around, you can use the MAX7219 LED Dot Matrix Display.  I rotate the display and put the register (or other data) row-wise into the display.

**Comment by urish** [comment]
Element released! 

Usage example: https://wokwi.com/arduino/projects/309829489359061570  
Docs: https://docs.wokwi.com/parts/wokwi-led-bar-graph
