### ISSUE TITLE
8 resistor bussed array

### ISSUE THREAD

**Issue by MykolaKyrylenko** [wokwi/wokwi-elements#105]
We are using the Arduino to teach low level register access (e.g. DDRx, PORTx, PINx) and we need to access all pins on a given port.
For convenience, can a 8 resistor bussed array be added. 330 ohms will be good.
Physical equivalent: https://au.rs-online.com/web/p/resistor-networks-resistor-arrays/1616842

Thanks

**Comment by urish** [comment]
Closing as this issue hasn't received any votes in 6 months
