### ISSUE TITLE
8-way SPST switch

### ISSUE THREAD

**Issue by MykolaKyrylenko** [wokwi/wokwi-elements#106]
We are using the Arduino to teach low level register access (e.g. DDRx, PORTx, PINx) and we need to access all pins on a given port.
For convenience, can an 8-way SPST slider switch be added.
Physical equivalent: https://au.rs-online.com/web/p/dip-sip-switches/8772148

Thanks.

**Comment by urish** [comment]
Switch is ready!

docs: https://docs.wokwi.com/parts/wokwi-dip-switch-8
