### ISSUE TITLE
Possible SVG enhancements

### ISSUE THREAD

**Issue by wilberforce** [wokwi/wokwi-elements#111]
I saw this acticle https://www.smashingmagazine.com/2020/01/recreating-arduino-pushbutton-svg/ and have been looking at optmising svgs with Lit Element.

1. Take a look here: https://jakearchibald.github.io/svgomg/
You can take your SVG output from inkscape and use this tool to shrink the SVG.
Using the pushbutton example:
1.36k → 643 bytes 46.33%
2. Instead of `fill="${color}"` your can use `fill="currentColor"` and then the element will pickup the colour from the parent element or element style

**Comment by urish** [comment]
Thanks for the suggestions!

Right now, optimizing the existing elements is not a priority, but I'll take these into account when working on future elements and [boards](https://github.com/wokwi/wokwi-boards).
