### ISSUE TITLE
Tiny fix to the Arduino Uno element SVG

### ISSUE THREAD

**Issue by arduino12** [wokwi/wokwi-elements#112]
This is a very small issue but as a hardware guy I can't ignore it (so many chips got fried due to this!)

**The bent at the top side of the atmega328 chip is missing!**
![image](https://user-images.githubusercontent.com/11454280/146656877-13aded62-6923-41b0-ba57-94a78fac463f.png)

It should look like **[this SVG](https://images.app.goo.gl/tf47keKCeLFno4TP7)**.

On the attiny85 it is right (Also with the pin1 dot mark!):
![image](https://user-images.githubusercontent.com/11454280/146656952-6bcb1d27-7f48-45f6-a189-335ea75a508d.png)

It also seen at the uno on the [wokwi page](https://wokwi.com/)

I would have created a PR, but I didnt find the uno.svg file.. so does the image is hard-codded in the [arduino-uno-element.ts](https://github.com/wokwi/wokwi-elements/blob/master/src/arduino-uno-element.ts)?

**Comment by urish** [comment]
Thanks for reporting! It's indeed hard-coded in that file

**Comment by urish** [comment]
Done!

**Comment by arduino12** [comment]
@AriellaE **Thanks!**

1. I think it will look better if you follow the [origal darker color](https://github.com/wokwi/wokwi-elements/blob/4a7caee452f2be6bd2b3f82cdf006c148429b0e1/src/arduino-uno-element.ts#L186-L187) - `fill="#252728"`
2. The [pin1 dot mark](https://github.com/wokwi/wokwi-elements/blob/4a7caee452f2be6bd2b3f82cdf006c148429b0e1/src/arduino-uno-element.ts#L188) doesn't look so good - so I think we better remove it.
3. Better copy the shape (half a circle path) from the [attiny85 board](https://github.com/wokwi/wokwi-elements/blob/4a7caee452f2be6bd2b3f82cdf006c148429b0e1/src/franzininho-element.ts#L189-L190) :)

By changing the [arduino-uno-element.ts](https://github.com/wokwi/wokwi-elements/blob/4a7caee452f2be6bd2b3f82cdf006c148429b0e1/src/arduino-uno-element.ts) extension from .ts to .svg and changing some numbers I made this:
![image](https://user-images.githubusercontent.com/11454280/147092980-4addc7c4-fbb5-4870-8bda-85281bb592a6.png)
By manually editing the text to:
```
  <g fill="#252728">
    <circle cx="33.269" cy="36.847" r="1" />
    <circle cx="59.939" cy="36.847" r="1" />
    <path d="M65 38.05a1.13 1.13 0 010-2.26v2.27z" />
  </g>
```
Made a [**PR**](https://github.com/wokwi/wokwi-elements/pull/113) :)
