### ISSUE TITLE
Visual glitch in potentiometer

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-elements#133]
When a potentiometer is turned with the mouse, the marker sometimes jitters to a other position.
It seems to happen in every browser.

There are two positions that cause it, and the marker always jumps to the minimum or maximum position.
It might take some time to find the glitch, but all three examples in the documentation have it: https://docs.wokwi.com/parts/wokwi-potentiometer

![glitch1](https://user-images.githubusercontent.com/12096541/180599554-d3f826fe-6150-4dab-9eaf-edcd58f4b03b.jpg)

![glitch2](https://user-images.githubusercontent.com/12096541/180599559-68a3ac90-8633-45b4-ba2b-c1bd50a67b8c.jpg)

When the potentiometer is rotated, the marker does not follow the mouse cursor. It also has that glitch.

![afbeelding](https://user-images.githubusercontent.com/12096541/180599686-a9081098-6288-4ede-ab34-a128224f3f55.png)
(The PrintScreen changed the cursor, it was a hand with pointing finger)

**Comment by urish** [comment]
Thanks for reporting! Can you please check again now?

**Comment by Koepel** [comment]
It has changed, but it is still there. When the mouse cursor is at 9 o'clock, then the marker jumps to the maximum.

https://user-images.githubusercontent.com/12096541/180612642-4a471d98-50bf-485c-9016-0f807729886a.mp4

The marker does not follow the mouse cursor when the potentiometer is rotated.

**Comment by urish** [comment]
How about now?

**Comment by Koepel** [comment]
I'm sorry, I meant to reply here, but I replied at: https://github.com/wokwi/wokwi-elements/issues/70#issuecomment-1193365746
Issue https://github.com/wokwi/wokwi-elements/issues/87 is something else in my opinion.

Latest tests: 
Works good without glitch and also rotated in: Chrome, Chromium, Edge, Vivaldi. In Windows and linux.
The potentiometer can no longer be used with Firefox in Windows and linux.
The Gnome Web browser (based on WebKitGTK) has no glitch, but a rotated potentiometer can not be used, although the marker moves a little.
The PaleMoon browser does not work with Wokwi at all, as we know. Nothing changed there.

**Comment by urish** [comment]
Thanks for the detailed tests!

It reproduces here.

I think #87 has the same underlying cause as what we're observing here - Firefox not implementing `getScreenCTM()` the same way other browsers do. They have an [open issue about it](https://bugzilla.mozilla.org/show_bug.cgi?id=1610093).

**Comment by Koepel** [comment]
It is now working here as well in Firefox.
Thank you.

The Gnome Web browser (based on WebKitGTK) has still troubles turning the knob. The WebKit is also used in Safari, but I can not test that.

**Comment by urish** [comment]
Thanks for testing! Applied the [same workaround for Epiphany](https://github.com/wokwi/wokwi-elements/commit/0bc20e8890b5aa6b541216112180958d76bdfd21), let's see if it does the trick

**Comment by Koepel** [comment]
Firefox works with the sliding potentiometer now.
The Gnome "Web" browser (Epiphany) has still trouble with the rotated round potentiometer. Perhaps that needs attention in a other issue.
This issue is fixed. Thank you.
