### ISSUE TITLE
Improve on the current stepper by allowing different sizes

### ISSUE THREAD

**Issue by bonnyr** [wokwi/wokwi-elements#138]
The current Stepper component is a fixed size and roughly the size of a Nema 17 stepper.
It would be useful to be able to select from a list of Nema sizes and have the component reflect the selection by being shown to scale.

I've created a PR : https://github.com/wokwi/wokwi-elements/pull/136 which implements this.

I believe there's no need for any additional code since it uses the same logic as the original stepper.

**Comment by urish** [comment]
Thanks! @AriellaE will be looking at the PR.

**Comment by bonnyr** [comment]
Is there anything else that needs to be done on my part to make this work?

**Comment by urish** [comment]
> Is there anything else that needs to be done on my part to make this work?

Not at the moment, we'll update you after reviewing the pull request. Thanks again for the contribution :)

> How do I earn the right to contribute to this repo?

The usual process is by creating a pull-request (like you just did). Do you have additional parts in mind?

**Comment by bonnyr** [comment]
> > How do I earn the right to contribute to this repo?
> 
> The usual process is by creating a pull-request (like you just did). Do you have additional parts in mind?

I have submitted another PR and created another issue for another part.
My question was more along the lines of what if there's more work needed by perhaps some changes needed to implement the new elements.

Another question of course is how this process can be opened so that others can help accept parts into the ecosystem
to prevent dumping all this load on you :)
