### ISSUE TITLE
The potentiometer is not keyboard accessible

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#14]
The potentiometer should be able to receive input focus and react to keyboard input, implementing the ARIA slider role:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role

This means we should respond to *Left*, *Right*, *Up*, *Down*, *Page Up*, and *Page Down* keys.
In addition, we could also support *Home* and *End* keys, similar to how `<input type="range">` to these events in chrome: setting the value to the start or end of the range.

You can check tinker with the current version of the potentiometer here: https://elements.wokwi.com/?path=/story/potentiometer--potentiometer

**Comment by LironHazan** [comment]
Can you pls assign to me :)
