### ISSUE TITLE
Add .js extension to export/import of javascript files in npm package

### ISSUE THREAD

**Issue by jogibear9988** [wokwi/wokwi-elements#149]
Hello,

I'm woring on a designer (https://node-projects.github.io/web-component-designer-demo/index.html) wich can directly import webcomponents from npm modules wich use esm code. But your npm packges is missing .js extension in the package, could that be added?

**Comment by urish** [comment]
Thanks for the request. Unfortunately, we don't have the bandwidth to look into this.
