### ISSUE TITLE
Potentiometer tooltip

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#15]
It would be nice to have an optional tooltip that shows the current value of the potentiometer. A good source of inspiration for that would be: https://js-rocks.web.app/stage

**Comment by LironHazan** [comment]
@urish since we're using svg and there's no z-index, what is the wanted position of the tooltip btw? (bottom/left/right/top)

**Comment by urish** [comment]
I think that for the tooltip itself, it will make sense to leave the SVG land...

**Comment by LironHazan** [comment]
@urish possible but let's keep stuff separated? we have a cool potentiometer component, I rather dispatch the value to another tooltip component and the story book will show the composition of both, what do you think? an overkill or a good practice?

**Comment by urish** [comment]
Make sense, I will close the issue then
