### ISSUE TITLE
cosmetic : buttons "shadow effect" mismatch

### ISSUE THREAD

**Issue by JM-FRANCE** [wokwi/wokwi-elements#153]
when using multiple buttons and selecting different Colors, the design looks good but when you start the simulation the Colors of the "circle" around the button used for a shadow/3D effect get mixed up and instead of using the specific color of the button, only one is used (may be the one from the last created button).

here is an image as it's easier to see than describe:

top screen grab is during design phase, bottom is during use after pressing the yellow button, the circle turned blue.
 
<img width="459" alt="image" src="https://github.com/wokwi/wokwi-elements/assets/15193091/384fb07d-94e0-44a9-bb95-6418dd60a871">

➜ that's ugly 😇🥶😱

**Comment by AriellaE** [comment]
Hello @JM-FRANCE 

I can't reproduce this bug.
Which browser do you use?  
Can you please send me a video showing how to reproduce this bug?

Thank you,
Ariella

**Comment by JM-FRANCE** [comment]
Hello,

I'm using Safari Version 16.5 on a Mac (OS X 12.6.6 Monterey). I can't record a video at the moment but here is a project (from the screen shot above) exhibiting the issue both on my Mac and on my iPhone (Safari / iOS 16.5.1).

https://wokwi.com/projects/368412397088476161

curious to know if you see the same ?

**Comment by Koepel** [comment]
Confirmed with "GNOME Web" browser (previous called Epiphany) version 44.1. It is a browser based on the WebKit engine.
![afbeelding](https://github.com/wokwi/wokwi-elements/assets/12096541/3eb1c5e0-13a6-4bfa-a5a1-ef2cc41a2560)

**Comment by JM-FRANCE** [comment]
confirmed it's working now in Safari

thanks.

**Comment by AriellaE** [comment]
Thank you @JM-FRANCE and @Koepel, 
It should be fine now.

Have a great day,
Ariella
