### ISSUE TITLE
wokwi-elements color palette 

### ISSUE THREAD

**Issue by LironHazan** [wokwi/wokwi-elements#17]
Suggestion:
Let's have a color palette with predefined colors as css variables? 
This way we'll achieve both code reusability and unified color theme

**Comment by urish** [comment]
Thanks for the suggestion! What kind of colors would we define in such palette?

**Comment by LironHazan** [comment]
Umm lets define several constants e.g. 
--knob-dark
--screen-green
--primary-font
I can ask a designer friend to go over it

**Comment by urish** [comment]
Other than the `--primary-font`, I think the other ones are specific for one component, no?

**Comment by LironHazan** [comment]
Yes, if you don't mind I'll go over the components again later on to think of a more generic names
