### ISSUE TITLE
Add rotary dialer element 

### ISSUE THREAD

**Issue by LironHazan** [wokwi/wokwi-elements#21]
A rotary telephone dial can provide a wonderful retro way to control and/or enter data into your Arduino-based projects. 

https://freesvg.org/rotary-dialer

Can watch following reference:

https://www.youtube.com/watch?v=t1nw5Jvnoxs

**Comment by LironHazan** [comment]
@urish using following reference for the size:
https://www.riecktron.co.za/product/4275

**Comment by urish** [comment]
Some more inspiration from @talofer99: 

https://www.youtube.com/watch?v=ldFT2dZi_Bc

**Comment by urish** [comment]
Implemented by #26
