### ISSUE TITLE
DHT11/DHT22 Sensor Elements

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#23]
These are very common temperature/humidity sensors. DHT22 is usually white:

![image](https://user-images.githubusercontent.com/892318/79884254-97810100-83fd-11ea-8ded-682d2b09c3e9.png)
[Source](https://commons.wikimedia.org/wiki/File:Maxdetect_Humidity_and_Temperature_Sensor_-_RHT03_10167.jpg)

While DHT11 is cyan:

![image](https://user-images.githubusercontent.com/892318/79884444-d7e07f00-83fd-11ea-85a6-f757cfacc6dd.png)
[Source](https://www.flickr.com/photos/adafruit/11211295045)

**Comment by LironHazan** [comment]
reference to the physical size https://learn.adafruit.com/dht

**Comment by urish** [comment]
We already have DHT22, so closing this issue
