### ISSUE TITLE
Add piezo electric buzzer

### ISSUE THREAD

**Issue by gfeun** [wokwi/wokwi-elements#24]
![](https://ke.jumia.is/zfOyg0GlNEocoVVI2LY0upb6iIM=/fit-in/500x500/filters:fill(white):sharpen(1,0,false):quality(80)/product/54/7543/1.jpg?9633)

**Comment by urish** [comment]
Thanks @gfeun! How does this buzzer works? It seems like it has a small MOSFET, and I guess that the resistor is connected to the gate of the mosfet?

**Comment by gfeun** [comment]
I don't know the implementation details. The physical principal is really simple and you may already know it. It uses the piezo electric property of a material which vibrates when current is applied to it. 
So when you apply an electric signal with a given frequency to it, it results in a sound of corresponding frequency.

We have a practical course where we teach students how to generate a signal of a given frequency using timers and apply it to a buzzer. We then ask the students to create a small piano using our 8 push buttons generating signals of different frequencies.

I'd like to make this possible to implement using avr8js.
Luckily you have already done most of the work as I've seen [here](https://stackblitz.com/edit/avr8js-simon-game) :smile:

**Comment by urish** [comment]
And now it's even being used!  🔊

https://wokwi.com/playground/spaceship-game
