### ISSUE TITLE
Rotary dialer emits two `dial` events per digit

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#27]
You can see the issue in this GIF:

![rotary-dialer](https://user-images.githubusercontent.com/892318/82748633-64d77900-9dac-11ea-9ee8-e9d7575adf3e.gif)

One event is emitted when the target digit hits the finger stop, and another one when the dialing animation finishes.

I suggest to change the behavior as follows:
* emit a `dial` event when the digit hits the finger stop (as it does now)
* emit a `dial-end` event when the animation finishes
* optionally emit a new `dial-start` event when dialing animation start 

This way, it would be analogous to keyboard/mouseevent, where you have a triplet of keydown/keypress/keyup or mousedown/click/mouseup events.

**Comment by LironHazan** [comment]
@urish can you assign to me? :)
