### ISSUE TITLE
Servo does not rotate properly on Safari

### ISSUE THREAD

**Issue by tawjaw** [wokwi/wokwi-elements#39]
Hello guys, 

The servo element does not rotate properly when using Safari on Mac. 
The Horn is moving in an arc instead of rotating in place.

<img width="1436" alt="Screen Shot 2020-07-30 at 4 02 19 PM" src="https://user-images.githubusercontent.com/10591561/88968936-19df5380-d27e-11ea-9a9c-4d19a8f98931.png">
<img width="1436" alt="Screen Shot 2020-07-30 at 4 01 48 PM" src="https://user-images.githubusercontent.com/10591561/88968963-2368bb80-d27e-11ea-82a7-ec1faabec1f9.png">

**Comment by urish** [comment]
Thanks for reporting! 

Seems like it might have to do with the [transform-origin attribute](https://github.com/wokwi/wokwi-elements/blob/de969e0f6277c6e0cedb17ecea81fff16053254b/src/servo-element.ts#L77).

**Comment by urish** [comment]
Fix published as part of 0.21.1
