### ISSUE TITLE
LCD 1602 Element

### ISSUE THREAD

**Issue by arcostasi** [wokwi/wokwi-elements#42]
I'm having fun in my spare time with your [avr8js](https://github.com/wokwi/avr8js) and [wokwi elements](https://github.com/wokwi/wokwi-elements), amazing project you are doing!
Most of the tests I did was through shared codes, at the moment I'm trying to do some tests with the lcd1602, but I haven't found any sample code for the controller and I'm having trouble getting it to work.
When you have time, could you help me with lcd1602 on my [playground project](https://github.com/arcostasi/avr8js-electron-playground) with Electron? Thanks!

**Comment by urish** [comment]
Wow, I'm impressed! This looks pretty slick 👍 

How long did it take you to create?
What plans do you have for it?

**Comment by arcostasi** [comment]
> How long did it take you to create?

it took me a few hours, 2 weeks ago I found avr8js and wokwi elements! very good! :)

> What plans do you have for it?

I don't have plans yet, I'm studying its components and I think we could create an offline and online development tool with its elements, I believe it could encourage and help many people, but I know it's not a very simple.

Do you have any idea? I saw that you implemented some wiring, and I found it very interesting!

**Comment by urish** [comment]
Very nice :) 

Right now, working on something similar to what you described on https://wokwi.com/arduino/libraries, but online only. I'm still experimenting with the user interface and the features, and also discussing potential features and ideas [with the FastLED community](https://www.reddit.com/r/FastLED/comments/ijgi7m/interactive_code_demos_for_fastled_run_in_browser/)

I'd love to see where the electron version goes!

**Comment by arcostasi** [comment]
Hi @urish, amazing working, I did some experiments with their libraries on the electron, it has been running with a very good performance! I would love to be able to take your wiring algorithm into Electron and to be able to open and save projects to files, it would be very interesting!
Great community that you sent, I will be following! ;) Thanks

**Comment by urish** [comment]
Hi Anderson, I have just `git pull`ed your project and it seems like you made a very nice progress on it!

I also see you managed to get the LCD 1602 to work, did you have to write the controller code from scratch? It does look better than mine for sure 👍 

Anything I can do to help you with the project?

**Comment by arcostasi** [comment]
Hi Uri, I'm glad you enjoyed it! I tried to create the controller based on your ssd1306.ts
The controller has a bug in the custom characters that I was unable to implement correctly and does not support to 8 bits.

Thank you so much, your help is very welcome!

Soon I will be trying to contribute to your wokwi components projects

**Comment by urish** [comment]
Here you go, custom character support: https://github.com/arcostasi/avr8js-electron-playground/pull/1

Also, I'm closing this issue (since the original problem is now resolved), but feel free to keep in touch here (GitHub), or email me at uri+avr8js@wokwi.com.
