### ISSUE TITLE
Using elements with VuePress

### ISSUE THREAD

**Issue by tawjaw** [wokwi/wokwi-elements#48]
Hello @urish 

I am facing a problem building a VuePress project using wokwi-elements. 

I get an error in the build saying "window is not defined"

The error happens just by doing 
`import '@wokwi/elements';`

even if I am not using any elements.

Any idea how I can work around this? 
Thank you

**Comment by urish** [comment]
Hi Taqfiw, my guess is that this happens as '@wokwi/elements' is imported in SSR (Server-Ride Rendering) environment, which runs inside Node.js, where `window` is not defined.

Depending on the exact setup, lazy-loading the module could do the trick. For instance, something along the lines of:

```typescript
if (typeof window !== 'undefined') {
  import('@wokwi/elements');
}
```

Depending on your setup, there could be a better way to distinguish between SSR and browser environment, but the above way should work regardless of the setup, as long as the import() syntax is supported.

**Comment by tawjaw** [comment]
Thanks @urish 

I couldn't import the module directly, but I was able to import files from `node_modules` after the component is mounted.

Inside the Vue component

```
mounted: function(){
    import("../../../../node_modules/@wokwi/elements/dist/esm/arduino-uno-element");

  },
```

That made it work with VuePress

**Comment by urish** [comment]
Glad you found a solution :-) What are you working on now?

btw, since version 0.17.0 (#30), you can also import wokwi-elements using a plain JavaScript <script> tag, e.g.

```html
  <script src="https://unpkg.com/@wokwi/elements@0.27.2/dist/wokwi-elements.bundle.min.js"></script>
```

**Comment by tawjaw** [comment]
I’m building a better version of the lab with an introduction to programming with Arduino + working on a 3D simulation of the robot.

I’m using VuePress cause it makes writing and managing the content of the pages easier by writing markdown files.

And it allows you to define Vue components and use them in the markdown files. 

After I’m done with this my plan is to work on the SD card simulation to collect data from sensors and then analyze them with python for a virtual hackathon we are planning for!

**Comment by urish** [comment]
Wow, I'm really looking forward to seeing this :)
