### ISSUE TITLE
Implement SSD1306 OLED Display

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#5]
It comes in several flavors, and different screen resolutions:
* 128x64 ([example](https://www.adafruit.com/product/326))
* 128x32 ([example](https://www.adafruit.com/product/931))
* 96x16 ([example](https://www.buydisplay.com/graphic-i2c-0-69-inch-96x16-oled-display-mp3-module-white-on-black))
* 64x48 ([example](https://www.sparkfun.com/products/13003))

**Comment by LironHazan** [comment]
@urish started to work on the svg part
