### ISSUE TITLE
OLED Image not aligned well on Safari

### ISSUE THREAD

**Issue by tawjaw** [wokwi/wokwi-elements#50]
Hello guys,

The display image doesn't align well on safari. 

<img width="183" alt="image" src="https://user-images.githubusercontent.com/10591561/98841442-1d09e400-2416-11eb-9786-e1843d2e9ad0.png">

**Comment by urish** [comment]
@LironHazan any chance you can take a look at this? I don't have a mac so it'll be a bit challenging for me to debug this
