### ISSUE TITLE
Implement a JoyStick

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#54]
Requested by wokwi/wokwi-features#40 and also on [discord](https://wokwi.com/discord).

Reference: https://www.adafruit.com/product/512

Open points:

- The real joystick also has a button inside it (Select), it's not obvious which user interaction would enable that. Perhaps double click/tap to select?
- Event names: we need to fire an event when the joystick moves with coordinates. I believe that -1.0 to 1.0 range of the axes would be a good choice. Ideally, we'll also have an event that fires when Select is pressed / released, but this depends on how we implement Select.

**Comment by sutaburosu** [comment]
To make it useful for games, and even some types of menu,  we must be able to move the joystick and press the button at the same time.  Mobile games often overlay big UI elements for this kind of thing,  so whilst the joystick is being held maybe superimpose a big circle in the corner of the screen to act as the button.

For desktop users I think dragging the joystick makes most sense,  with WSAD as shortcuts for the 8 cardinal directions.  For the button double-click is good,  but to use it whilst dragging I guess Space/Enter could be used.

**Comment by urish** [comment]
Preview: https://elements.wokwi.com/?path=/story/analog-joystick--joystick
