### ISSUE TITLE
unable to solve the problem

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-elements#58]
https://wokwi.com/arduino/projects/293236942293697034

![image](https://user-images.githubusercontent.com/68117142/111343970-f26cb800-86a1-11eb-8500-ae43366a7b63.png)

what might be the issue?
![image](https://user-images.githubusercontent.com/68117142/111344128-1cbe7580-86a2-11eb-8d9f-d77ce3d8e048.png)

**Comment by urish** [comment]
Change the include to use " instead of <, e.g.

```cpp
#include "SolomonSystech.h"
```

also, make sure you include the "TinyWireM" library, by commenting out the following line:

```cpp
#include <TinyWireM.h>
```
