### ISSUE TITLE
Add Rotary Encoder KY-040 to parts list

### ISSUE THREAD

**Issue by acitonic** [wokwi/wokwi-elements#64]
I need a touch and turn encoder for controlling a menu on a display

**Comment by urish** [comment]
User manual: https://www.epitran.it/ebayDrive/datasheet/25.pdf
Mechanical drawing (dimensions in MM): https://cdn.thingiverse.com/assets/96/48/c5/0b/d4/ROT-KY040-S_04-600x480.jpg

**Comment by jimf99** [comment]
Looking forward to seeing this added!
Thanks WokWi Team!
Kind Regards from Calgary Alberta Canada

**Comment by urish** [comment]
Documentation for the new part: https://docs.wokwi.com/parts/wokwi-ky-040
