### ISSUE TITLE
wokwi-potentiometer usability issues when rotated

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#70]
Example: https://wokwi.com/arduino/projects/299392610996322826 (rotating the potentiometer by 142 degrees). 

180 degrees seem to be the most confusing. 

A good place to start looking is the slide-potentiometer implementation (#63), where a similar issue has been fixed using the inverse of the matrix returned by `getScreenCTM()`.

**Comment by urish** [comment]
Fixed!

**Comment by Koepel** [comment]
In Chromium, the potentiometer can be rotated and the glitch is gone.
In Firefox, the potentiometer can no longer be used.

**Comment by urish** [comment]
Thanks for reporting! I suspect that the firefox issue is related to #87.
