### ISSUE TITLE
Minimum font size makes text labels very big.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-elements#78]
In the Firefox browser I have set the minimum font size to 10.
This is the result:
![1](https://user-images.githubusercontent.com/12096541/120656582-05fb1400-c484-11eb-8d78-4db966b97b5a.png)
Everything is normal when I turn off the minimum font size:
![2](https://user-images.githubusercontent.com/12096541/120656631-0f847c00-c484-11eb-8f77-a8fb970301d0.png)
But I don't want to turn it off. I always set a minimum font size.

**Comment by urish** [comment]
Thanks for reporting!

Interestingly, this only seems to affect certain texts, while not affecting others (e.g. the top pin labels)....

Does this affect other [elements](https://elements.wokwi.com) as well?

**Comment by Koepel** [comment]
Other elements with the same problem are the Mega, Nano, OLED, LCD.
![Schermafdruk op 2021-06-03 16-43-08](https://user-images.githubusercontent.com/12096541/120664829-8b35f700-c48b-11eb-8f2b-fa5c0b038c2b.png)
![Schermafdruk op 2021-06-03 16-44-57](https://user-images.githubusercontent.com/12096541/120664844-8ec97e00-c48b-11eb-8fc8-3a82a57fb626.png)
![Schermafdruk op 2021-06-03 16-43-31](https://user-images.githubusercontent.com/12096541/120664880-9721b900-c48b-11eb-9fab-24a1896aa0bb.png)
![Schermafdruk op 2021-06-03 16-44-14](https://user-images.githubusercontent.com/12096541/120664977-a99bf280-c48b-11eb-99bb-4bdf8d007722.png)

There are no problems with Pico, DHT, RTC.
![Schermafdruk op 2021-06-03 16-42-35](https://user-images.githubusercontent.com/12096541/120665026-b6b8e180-c48b-11eb-9e8c-936439dc711e.png)
![Schermafdruk op 2021-06-03 16-44-37](https://user-images.githubusercontent.com/12096541/120665067-be788600-c48b-11eb-9235-b4ccc78b64a3.png)
![Schermafdruk op 2021-06-03 16-44-40](https://user-images.githubusercontent.com/12096541/120665102-c506fd80-c48b-11eb-9bb4-6eb6304c4447.png)

**Comment by urish** [comment]
Alright, so we'll investigate to see what causes the difference

**Comment by urish** [comment]
Released as wokwi-elements 0.40.1

**Comment by Koepel** [comment]
All the elements are okay, but the website uses a "Loading..." display which still has them.

![big](https://user-images.githubusercontent.com/12096541/121225976-57dbd980-c88a-11eb-8529-84e992c82e68.png)

**Comment by urish** [comment]
Good catch, fixed! 

Thanks for reporting :)

**Comment by Koepel** [comment]
Can the new ST Nucleo be fixed as well ?
![afbeelding](https://github.com/wokwi/wokwi-elements/assets/12096541/f239bd40-735b-4486-9132-50f4da973f38)

**Comment by AriellaE** [comment]
Hello @Koepel,
I fixed it.
Thank you for reporting.

**Comment by Koepel** [comment]
I found another one, the "wokwi-photoresistor-sensor":
![afbeelding](https://github.com/wokwi/wokwi-elements/assets/12096541/5f79adfa-28c7-4bc2-9c9e-fa4faa4aa41f)

**Comment by AriellaE** [comment]
Thank you @Koepel,
Should by fine now 🙂

**Comment by Koepel** [comment]
The ESP32-S3
![afbeelding](https://github.com/wokwi/wokwi-elements/assets/12096541/9aaadb57-cb57-47b6-a083-a472db33c19a)

**Comment by Koepel** [comment]
These boards have very big text labels:
* board-esp32-devkit-c-v4
* board-esp32-s3-devkitc-1
* board-st-nucleo-l031k6
