### ISSUE TITLE
SSD1306 artifacts

### ISSUE THREAD

**Issue by costyn** [wokwi/wokwi-elements#79]
When drawing on the OLED, it seems there are some artifacts which don't show up on the real OLED display. 

In my project you can see them in the bottom of the QR code. A memcpy gone wrong? Or index of out bounds?
https://wokwi.com/arduino/projects/298044628807975432

**Comment by urish** [comment]
I just checked this project on a physical SSD1306 OLED display and it shows the same artifacts:

![image](https://user-images.githubusercontent.com/892318/121824304-e0f07780-ccb3-11eb-9402-1fadc5397598.png)

Are you sure you are getting different results with Arduino Uno + a physical SSD1306 OLED display module?

**Comment by urish** [comment]
If you switch (in the simulation) to `wokwi-arduino-mega` then it seems to work fine. So I suspect this is caused by the program using too much SRAM

**Comment by costyn** [comment]
Interesting. I connect it here to an ESP32, and no artifacts. So yea it seems to be a UNO related issue. Good to know, thanks.

**Comment by urish** [comment]
Yes, generally - when you test ESP32 code on the Uno, you can fake larger SRAM, so you don't run into memory issues. Just add `      "attrs": { "__fakeRamSize": "65000" }` to the wokwi-arduino-uno part in diagram.json. Here's an example:

https://wokwi.com/arduino/projects/301360621680591373
