### ISSUE TITLE
Add Arduino Nano Element

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-elements#8]
The board needs to include at least the male pin headers, the Mini-USB connector, 4 LEDs (TX, RX, Power, L), the microcontroller itself, and the ICSP programmer pins (can be seen on the right side of the board). Nice to have elements: reset button (which should also emit reset-press/reset-release events, similar to the [pushbutton element](https://github.com/wokwi/wokwi-elements/blob/master/src/pushbutton-element.ts).

As a reference, check out the implementation of the Arduino Uno Element. You can reuse most of the part, especially the pattern for drawing the pin headers, USB/power jacks, LEDs, and the ICSP programmer pins.

Reference images:

[![Arduino Nano](https://user-images.githubusercontent.com/892318/77750844-91357a00-7035-11ea-9525-742fdddc0054.png)](https://www.piqsels.com/en/public-domain-photo-zadii)

License: CC0

[![Arduino Nano](https://upload.wikimedia.org/wikipedia/commons/7/78/Arduino_nano.jpg)](https://upload.wikimedia.org/wikipedia/commons/7/78/Arduino_nano.jpg)

License: CC-BY-SA

Mechanical drawings:
[![Ardunio Nano Machanical Drawing](https://nulliusinverba915909567.files.wordpress.com/2018/11/arduino-nano-v30-atmega328-blue-4.jpg)](https://nulliusinverba.blog/tag/mechanical-drawing/)

[![Arduino Naon Mechanical Drawing](https://components101.com/sites/default/files/inline-images/Arduino-Nano-Dimensions.png)](https://components101.com/microcontrollers/arduino-nano)

**Comment by sutaburosu** [comment]
@urish I'm a total noob to Node, Typescript, SVG, graphic design and webdev in general.  I learned a huge amount from your tutorial videos and yesterday's commit adding the Mega.  There's no rush for this, right?  I think I can do this,  but it will take me a while.  I may need help later getting the reset button to work.

My only progress so far is this pattern for unsoldered pins.  Good enough?
![image](https://user-images.githubusercontent.com/20606/92040131-2c154b80-ed6e-11ea-86bc-8914b43652a9.png)

```
import { svg } from 'lit-element';

export const pinsPlatedThroughHolePattern = svg`
  <defs>
    <filter id="solderPlate" style="color-interpolation-filters:sRGB;">
      <feTurbulence result="r0" type="fractalNoise" baseFrequency="1" numOctaves="3"/>
      <feComposite  result="r1" in="r0" in2="SourceGraphic" operator="arithmetic"
        k1="0.6" k2="0.6" k3="1.2" k4="0.25"/>
      <feBlend      result="r2" in="r1" in2="SourceGraphic" mode="luminosity"/>
      <feComposite  result="r3" in="r2" in2="SourceGraphic" operator="in"/>
    </filter>
  </defs>
  <pattern id="pins-pth" width="2.54" height="2.54" patternUnits="userSpaceOnUse">
    <circle r="0.750" cx="1.27" cy="1.27" style="fill:#323232; filter:url(#solderPlate)"/>
    <circle r="0.375" cx="1.27" cy="1.27" style="fill:#ffffff"/>
  </pattern>
  <pattern id="pins-gold-pth" width="2.54" height="2.54" patternUnits="userSpaceOnUse">
    <circle r="0.750" cx="1.27" cy="1.27" style="fill:#484800; filter:url(#solderPlate)"/>
    <circle r="0.375" cx="1.27" cy="1.27" style="fill:#ffffff"/>
  </pattern>
`;
```
