### ISSUE TITLE
Slide potentiometer does not work correctly on Firefox

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-elements#87]
link: https://wokwi.com/arduino/projects/301206238041997832

I am not able to move the potentiometers easily. More or less it is impossible sometimes. here is a small video.
![RTC on wokwi Arduino Simulator bug guess](https://user-images.githubusercontent.com/68117142/122675462-2c94ab00-d1f7-11eb-914b-91cc8cf770ba.gif)

**Comment by urish** [comment]
@Spinkelben mind looking into this? This reproduces for me on Firefox in the [slide-potentiometer storybook](https://elements.wokwi.com/?path=/story/slide-potentiometer--default)

For now, a workaround would be to use the keyboard shortcut to move the knob. First, click on it to focus, then up/down for a very subtle movement, page up/page down for coarse movement, and home/end to quickly get to the extremes

**Comment by urish** [comment]
Fixed!

**Comment by Spinkelben** [comment]
Sorry for not responding, I somehow missed the notification!
