### ISSUE TITLE
feature request - LED light to match the lit color

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-elements#93]
![image](https://user-images.githubusercontent.com/68117142/126151006-5e78a76d-befc-4b6f-a980-851efa45cee2.png)

When I set the LED colour to Blue/Green/White/Red --> The LED light colour also automatically changes to the body colour of the LED. 

If I set the LED colour to Lime, for example, the body colour will change but not the colour of the light. 
Is there any reason for this or can it be made to glow in the same colour as the body colour of the LED (automatically, instead of` "lightColor": "orange"`)?

**Comment by urish** [comment]
Currently, the light color are defined [here](https://github.com/wokwi/wokwi-elements/blob/eb00a97c95965738dca2c831ca23efde2470bc00/src/led-element.ts#L5). When there's no definition, we use a fallback value of [#ff8080](https://github.com/wokwi/wokwi-elements/blob/eb00a97c95965738dca2c831ca23efde2470bc00/src/led-element.ts#L51).
