### ISSUE TITLE
SSD1306 - Screen content offset on Safari

### ISSUE THREAD

**Issue by gabrielcsapo** [wokwi/wokwi-elements#95]
Hello!

Awesome work on wokwi! Super awesome! 

I was playing around with https://wokwi.com/arduino/libraries/Adafruit_SSD1306/ssd1306_128x64_i2c when I saw that the screen content was offset. I wanted to contribute back some fixes, but didn't know where to do that.

<img width="1792" alt="Screen Shot 2021-07-21 at 6 43 58 PM" src="https://user-images.githubusercontent.com/1854811/126579831-1a6de52f-aa34-4119-bfe5-5a0987581e02.png">

**Comment by urish** [comment]
We already had a similar issue in the past: #50.

@gabrielcsapo if you are up to contributing a fix, the source code is at [src/ssd1306-element.ts](https://github.com/wokwi/wokwi-elements/blob/master/src/ssd1306-element.ts]. Otherwise, Ariella will take a look at it some time next time.
