### ISSUE TITLE
HX711 Load Cell Amplifier

### ISSUE THREAD

**Issue by arcostasi** [wokwi/wokwi-elements#99]
HX711 24-Bit Analog-to-Digital Converter (ADC) for reading load cells/weight scales.

A load cell or a Strain Gauge is basically a  Transducer which generates an electrical signal whose magnitude is proportional to the force applied. The various load cell types include Pneumatic, Hydraulic, and strain gauge.

The load cells or Strain gauges can be used in different automation projects. The load cells can be used for the precise weight measurement if properly calibrated. The load cells are commonly used in industrial processes where the weight of certain products is measured. The load cells can be used in automatic bag filling machines. The load cells or strain gauges can be used in infinitely different ways.

HX711 has different gain values which are selectable 32, 64 and 128.  Any of the mentioned gains can be selected and used in the programming.

### Technical Specifications
- Operating voltage 4.8-5.5V DC
- Operating current: 1.6mA
- Operating temperature: -20 to 85°C
- SPI Interface
- Dimensions: 29 x 17 x 4mm (without pins)

### Pinouts

![HX711-module-pinout](https://user-images.githubusercontent.com/5041497/127872767-be92567c-383e-4471-916b-47fd4a9361ef.png)

### Documents

- HX711 Module [Datasheet](https://img.filipeflop.com/files/download/Datasheet_HX711.pdf)

### Library

- [HX711 Arduino Library](https://www.arduino.cc/reference/en/libraries/hx711-arduino-library/)

### Code

```cpp
#include "HX711.h"

const int LOADCELL_DOUT_PIN = 2;
const int LOADCELL_SCK_PIN = 3;

HX711 scale;

void setup() {
  Serial.begin(9600);
  scale.begin(LOADCELL_DOUT_PIN, LOADCELL_SCK_PIN);
}

void loop() {
  if (scale.is_ready()) {
    long reading = scale.read();
    Serial.print("HX711 reading: ");
    Serial.println(reading);
  } else {
    Serial.println("HX711 not found.");
  }
  delay(1000);
}
```

**Comment by yepher** [comment]
This is the same as issue #101 

I created a PR #116 for this

**Comment by urish** [comment]
Part is ready!
